# Generated by Django 6.1 on 2026-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_review_alter_momo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
